### PR TITLE
Amended Commit for Pull Request #5

### PR DESCRIPTION
**Pull request by Enijar**

### CODE REVIEW

**Comment by Enijar** [comment]
@pongstylin Or we could make two webpack configs inside a config directory: one for production and one for development? Similar to [this](https://github.com/carloluis/webpack-demo/tree/master/config).

**Comment by pongstylin** [comment]
There is too much in common between the dev and prod modes right now to persuade me to split the files.

**Comment by Enijar** [comment]
Just a thought. We’ll have to see if the dev and prod builds vary in the future.

**Comment by Enijar** [comment]
@pongstylin any chance of this getting merged in when you get a chance?

**Comment by pongstylin** [comment]
Need to give it another round of testing, first

**Comment by pongstylin** [comment]
I tested it.  I don't love the fact that "npm run dev" just hangs in the foreground as well as "npm start".  That's two hanging windows while you do development.  Could we reduce it to one command that starts the server and watches for changes?  That same window will output any debugging information or let us know if it caught a change and is rebuilding bundles.

Also, the "--mode" argument still needs to be removed.

**Comment by Enijar** [comment]
We can do something like this

```bash
npm start & npm run dev
```

But I'm not sure this will work on Windows. In the case to support Windows devs we can use something like a make file or a bash script (if that's supported). Will need to consult a Windows machine to see if this will work.

**Comment by Enijar** [comment]
@pongstylin Can you confirm `npm start & npm run dev` works on your Windows machine.

**Comment by pongstylin** [comment]
Please give me access to push a commit to your pull request.  I had trouble using the asynchronous syntax within cross-env, so I dug a little deeper and realized that I didn't need cross-env at all.  Since I use git bash on windows, I was able to configure npm to use it when running scripts.

**Comment by pongstylin** [comment]
That doesn't seem to be what I need.  Check out this article:
https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/

**Comment by Enijar** [comment]
I already did that. Can you not make commits?

Screenshot

**Comment by Enijar** [comment]
I can't see the commit. Did you commit it to this repo or my fork?

**Comment by pongstylin** [comment]
I see my mistake.  I did push it to my repository.  I'll merge it anyway and you can submit a new pull request with further changes, if needed.

**Pull request closed without merging**
