### PR TITLE
Add HP bars

### PR DESCRIPTION
**Pull request by lime-green**
This PR adds hp bars to the card, addresses https://github.com/pongstylin/tactics/issues/25

### CODE REVIEW

**Comment by pongstylin** [comment]
I love that you're using a 2d canvas to achieve gradients.  That demonstrates skill and a drive to artistic perfection.  I haven't yet had a chance to exercise the code and see the effect, but will before I approve this.  In the meantime, I did review the code.  I have two questions:

1. I see that you are drawing the health bar and creating the canvas in the unit object.  This implies that there is one canvas created (and cached) per unit.  Why did you place the code in the Unit class instead of the Board class?
2. I don't see you using a mask anywhere.  I assumed a mask would be necessary to cut our a curved region of the gradient rectangle to achieve the curved-up effect at the start of the health bar.  I would approve a rectangular health bar, but making it curved would be a nice stretch-goal.

FYI: I intend to eventually create an issue for breaking out card management to its own class using ES6 syntax.  The Card class would accept a unit object as input and would, again, only cache one canvas object for the purposes of drawing the health bar.

**Comment by lime-green** [comment]
Hey Dave, thanks for the kind words :)

1. The canvas object is passed as a reference to `PIXI.Texture.fromCanvas`. This means that sharing a single canvas objects between the units will result in a single canvas object being shared. 
2. The [parallelogram](https://en.wikipedia.org/wiki/Parallelogram) (I had to look that up haha!) is achieved with the `lineTo` commands. There could be a better way to do this so let me know!

**Comment by pongstylin** [comment]
I finally had a chance to look at it.  It looks great, but I have some adjustment requests.  If any of them are too hard or time consuming, let me know and I'll merge your work.

1.  I'm not sure where its from, but I had a different shape in mind for the health bar.  But, you're right.  The shape matches the original.  I have a few tweaks that should give the various card components a little more room to breath:
    - Raise the title text position slightly (4px?).  I don't intend to ever place wait turns above the title text.
    - Decrease the height of the health bars slightly.  (1-2px)
    - Lower the health bar position slightly.  (2-4px)
    - Try setting strokeThickness to 2 to improve contrast between overlapped text and health bar.  (I found it difficult to read when bar is yellow).
    - (tricky) Right-align the notice text.  That is, determine how wide it is and position the "x" coordinate such that the right-edge is on or just adjacent to the right-edge of the card.
2. Looks like you're only caching the canvas on each unit.  It doesn't look like you're caching the entire health bar for each unit (and only update when the health changes).  That's fine (I don't think we need an additional performance optimization), but it does mean there is only one health bar.  So I don't see an issue with changing the health bar for one unit impacting all the units.  Every time we "drawCard", the health bar is drawn from scratch (using one cached shared canvas) for the unit being carded.  Do you think this is a good idea?
3. When a unit is attacked, I see a dramatic shift from green to yellow.  I'm still studying the right approach for fixing that.  So expect more from me on this unless you have an idea on how to make the transition more smooth.

**Comment by lime-green** [comment]
@pongstylin Sounds good, thanks for the feedback. You're right about the canvas stuff, at least for the cards, we can share one global canvas since there's only one global card. Also it makes sense not to re-draw if the health hasn't changed.

I'll start working on this tonight. Thanks again

**Comment by lime-green** [comment]
@pongstylin Made the changes, let me know what you think. The health bar does indeed look better with the new triple gradient

**Comment by pongstylin** [comment]
Yes, this is brilliant work.  Definitely moving in the right direction.  I particularly like how you improved on my instructions by using a yellow-green color and made use of the "anchor" feature for aligning text (I didn't know about this feature).  I'm also quite pleased with the strokeThickness of 2.  The overlap of text and health bar is stylish, perfectly readable, and closely resembles the original game.  But we're not done yet!  I have a few more requests.

1. There's a bug.  You're using a "7px" font for the notice text.  For one, this is way too small.  For two, it is temporary and only noticeable when you first load the "classic" app and the champion tells you which team goes first.  The reason is because the font size is changed after its initial definition.  The font size may be either 11px or 13px depending on whether the notice represents unit status (e.g. paralyzed) or a temporary notice (e.g. attack chances) respectively.  Now that the notice has a different position, the 13px font size is arguably too large.  Please reconcile all of this in a way that seems attractive/readable to you.
2. It's a little odd seeing the Champion message offset.  This is because the position of the notice text is fixed to not conflict with the health bar.  But the champion doesn't have a health bar.  Please position the notice text conditionally based on whether it is displaying a "unit" in the card or the champion.  Essentially, all champion notices should be centered like they were before.
3. The offset notice text could be shifted more to the right.  The card width is 176, but the notice is currently set to 170.  I recommend 174 since I think a slight indent looks good.
4. Play around with attacking a unit.  Not only will you see your very slick health bar shrink and change in color, but you will see duplicate health numbers decrementing, which doesn't look very good at all.  The board has a "playResults" method that applies the duplicate numeric notice.  Please remove.

**Comment by lime-green** [comment]
@pongstylin comments addressed

**Comment by pongstylin** [comment]
Looks good!  I agree with the consistent 11px font size choice.  Since I'm super obsessive about the details, I'm going to tweak on this a little more.  But it isn't significant enough to trouble you over.  Thank you very much for tackling this.  I really wanted to get to this, but I couldn't justify it over the higher priority of getting server-based multiplayer in place.

You are welcome to work on other issues that already exist or create your own.  You can also join us on our discord to discuss potential changes.
https://discord.gg/ASb2pr

**Pull request merged**
