### PR TITLE
Feature - Auto refresh game list page

### PR DESCRIPTION
**Pull request by MainShayne233**
This is an attempt at implementing the feature request described in: https://github.com/pongstylin/tactics/issues/71

The high levels are:
- The game fetching logic has been broken out into a function called `fetchGames`
- Another function called `fetchAndRenderGames` has been implemented to facilitate fetching then rendering
- The main game render function now clears the game lists `<div/>`s prior to rendering.
- An interval is setup to call on `fetchAndRenderGames` every 30 seconds

### CODE REVIEW

**Comment by pongstylin** [comment]
Great work.  I request that you make 2 changes before I merge this.  First, it refreshes every 30 seconds.  But I would rather it refresh every 5 seconds.  Second, it has a performance issue.  It sets an interval that runs even when the tab goes into the background (e.g., by switching tabs).  But, when the tab goes into the background, I disconnect from the server.  So, it is queuing a potentially large number of search requests in the background.  Once the user reactivates the tab, all of those queued requests are submitted to the server at one time.

There are 2 ways I can think of to address this.  Either you stop and start the interval as the tab is activated/deactivated, or you put in a simple throttling mechanism that prevents sending a new request if the last request hasn't resolved yet.

Let me know if you are unable to work on this so that I know to do it for you.

**Comment by MainShayne233** [comment]
Awesome, that makes sense! I'll make those changes!

**Comment by MainShayne233** [comment]
@pongstylin I made the requested changes!

I decided to go with using [`ifvisible.js`](https://github.com/serkanyersen/ifvisible.js) to detect whether or not a request for the updated games list should be made.

This seemed like the simplest way to avoid polling when the tab isn't active, but did require adding a new dependency, so lemme know if that trade off is worth it to you.

**Comment by pongstylin** [comment]
Thanks.  That seems to work.  But I found something else that doesn't.  If a game ends, it is not cleared from the list without refreshing.  There is no code that clears the games.* sets.

**Comment by MainShayne233** [comment]
Ah, I guess I neglected that bit. I’ll add the code to make sure it gets cleared.

**Comment by MainShayne233** [comment]
@pongstylin Determined that the issue was that the game `Map`s weren't being cleared before being re-hydrated was the newly fetched games, so now the get cleared when the DOM does.

Also, found a small bug in the error handler for the fetch and fixed that.

**Comment by pongstylin** [comment]
Thanks,  It keeps getting better and better.  I found another glitch, though.  In my test scenario, I opened the game in two windows side-by-side on my windows PC.  I had the game list on the left and was creating games, joining games, ending games, on the right to see if the game list on the left would update accordingly.  It didn't until I restored focus to the left window.  Either visiblejs doesn't support this or it isn't configured to support this, but I don't disconnect from the server simply because the page loses focus.  I only disconnect from the server if the page becomes hidden, e.g. minimized or is not the active tab.  In this case, your interval stopped refreshing because the page lost focus, but is still visible.

It might be best if we didn't use visiblejs at all.  Rather, you can make the refresh logic agnostic about whether or not the server is connected or the page is visible by simply avoiding parallel or stacked requests, which is the main performance concern.  If a request is still pending, don't submit a new request.  Otherwise, submit a new request.  This would also catch cases where the user lost internet connectivity.  We don't want a bunch of requests stacking up until connection is restored either.

**Comment by pongstylin** [comment]
P.S.  I can think of two ways to avoid stacked requests.  Either maintain a higher scope variable that keeps track of whether a request has finished or use setTimeout instead of setInterval.  Basically, set a timeout for 5 seconds after the list is refreshed.

**Comment by MainShayne233** [comment]
That all makes sense! Thanks for the very in-depth description of the issue and possible solutions. Your proposed solutions sound promising, so I’ll give them a go and see what I can iron out.

**Comment by MainShayne233** [comment]
@pongstylin I think I got it working with `setTimeout`! I manually verified that it wouldn't spam requests by shimming in a `window.requestCount` and verified that a server disconnect would result in not continuing to attempt fetches.

**Comment by pongstylin** [comment]
Looks good to me!  And the code style looks pretty clean as well - although I would only push back on code style if it is of significant concern.  I've merged this to master and will now release it to the beta server and will release to the playground server with everything else on the normal monthly cadence, May 1st.  Thanks!

**Comment by MainShayne233** [comment]
Thank you! I found you to be a very nice and helpful maintainer :-)

**Comment by pongstylin** [comment]
Are you on the TAO discord chat... or at least the TAO Facebook group?

**Comment by MainShayne233** [comment]
@pongstylin I'm on neither!

**Comment by pongstylin** [comment]
well, I at least recommend that you join the discord.  It would also be helpful if you intend to help out some more on this project since we can collaborate more easily.  Lots of old TAO players hang out there and are currently playing the first TAO tournament in years.  Here is an invite link.

https://discord.gg/juyhghF

**Pull request merged**
